### ISSUE TITLE
Create alternate dockerfiles for development

### ISSUE THREAD

**Issue by christophergeiger3** [christophergeiger3/the-clipping-project#37]
1. [x] Add `Dockerfile.dev` files to `api` and `web`
2. [ ] Consider mounting _all_ code files into docker https://vsupalov.com/rebuilding-docker-image-development/
3. [x] Add `docker-compose.dev.yml` which calls the new development docker files, e.g.
```yml
services:
  web:
    build:
      dockerfile: web/Dockerfile.dev
```
4. [ ] Update the docs to demonstrate how the docker development build can be launched
